services:
  wireguard:
    image: qmcgaw/gluetun
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - PUID=1000
      - PGID=1000
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
    ports:
      - 9091:9091/tcp
    volumes:
      - /mnt/Torrents/wg-docker/wg0.conf:/gluetun/wireguard/wg0.conf
      - /lib/modules:/lib/modules
    restart: always 
  transmission:
    image: ghcr.io/linuxserver/transmission:4.0.3
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - TRANSMISSION_WEB_HOME=/config/webtheme
      - USER=
      - PASS=
    volumes:
      - /mnt/Torrents/transmission-config:/config
      - /mnt/Torrents/downloads:/downloads
      - /mnt/Torrents/downloads/watch:/watch
    network_mode: "service:wireguard"
    depends_on: [ "wireguard", ]
    restart: always
